'use client';
import {useEffect,useState} from 'react';
import {Headphone} from '../lib/headphones';
import {useCases} from '../lib/categories';
import ProductCard from './ProductCard';
export default function Catalog({items}:{items:Headphone[]}) {
 const [q,setQ]=useState(''),[brand,setBrand]=useState(''),[use,setUse]=useState(''),[design,setDesign]=useState(''),[connection,setConnection]=useState(''),[anc,setAnc]=useState(''),[sort,setSort]=useState('brand');
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setQ(p.get('q')||'');setBrand(p.get('brand')||'');setUse(p.get('use')||'');setDesign(p.get('design')||'');setConnection(p.get('connection')||'');setAnc(p.get('anc')||'');},[]);
 function update(key:string,value:string,set:(v:string)=>void){set(value);const p=new URLSearchParams(window.location.search);value?p.set(key,value):p.delete(key);window.history.replaceState(null,'',window.location.pathname+(p.size?'?'+p:'')+'#catalog');}
 const filtered=items.filter(h=>(h.brand+' '+h.model).toLowerCase().includes(q.toLowerCase().trim())&&(!brand||h.brand===brand)&&(!use||h.uses.includes(use))&&(!design||h.design===design)&&(!connection||h.wireless===(connection==='wireless'))&&(!anc||h.anc===anc)).sort((a,b)=>sort==='model'?a.model.localeCompare(b.model):(a.brand+a.model).localeCompare(b.brand+b.model));
 const reset=()=>{setQ('');setBrand('');setUse('');setDesign('');setConnection('');setAnc('');window.history.replaceState(null,'',window.location.pathname+'#catalog');};
 return <><div className="filters"><label className="search-label">Find a model<input type="search" placeholder="Brand or model…" value={q} onChange={e=>update('q',e.target.value,setQ)}/></label><label>Brand<select value={brand} onChange={e=>update('brand',e.target.value,setBrand)}><option value="">All brands</option>{[...new Set(items.map(h=>h.brand))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>Use case<select value={use} onChange={e=>update('use',e.target.value,setUse)}><option value="">All uses</option>{useCases.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label><label>Design<select value={design} onChange={e=>update('design',e.target.value,setDesign)}><option value="">All designs</option>{['open-back','closed-back','semi-open'].map(x=><option key={x}>{x}</option>)}</select></label><label>Connection<select value={connection} onChange={e=>update('connection',e.target.value,setConnection)}><option value="">All connections</option><option value="wired">Wired only</option><option value="wireless">Wireless capable</option></select></label><label>ANC<select value={anc} onChange={e=>update('anc',e.target.value,setAnc)}><option value="">Any ANC status</option><option value="yes">Confirmed ANC</option><option value="not-applicable">Passive wired</option><option value="not-verified">Not verified</option></select></label></div><div className="results-bar"><p role="status" aria-live="polite">{filtered.length} of {items.length} models</p><button onClick={reset}>Reset filters</button><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="brand">Brand A–Z</option><option value="model">Model A–Z</option></select></label></div>{filtered.length?<div className="product-grid">{filtered.map(h=><ProductCard key={h.slug} h={h}/>)}</div>:<div className="notice"><h3>No matching models</h3><p>Try fewer filters or a shorter model name.</p><button onClick={reset}>Show all models</button></div>}</>;
}
