'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {headphones,ancLabel,specLabels,Headphone} from '../lib/headphones';
import ProductImage from './ProductImage';
const valid=(ids:string[])=>[...new Set(ids)].filter(id=>headphones.some(h=>h.slug===id)).slice(0,4);
export default function Compare(){
 const [ids,setIds]=useState<string[]>([]),[different,setDifferent]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const sync=()=>setIds(valid((new URLSearchParams(window.location.search).get('models')||'').split(',')));sync();window.addEventListener('popstate',sync);return ()=>window.removeEventListener('popstate',sync);},[]);
 const change=(slot:number,value:string)=>{const next=[...ids];if(value)next[slot]=value;else next.splice(slot,1);const clean=valid(next);setIds(clean);setMessage('');window.history.replaceState(null,'','/compare/'+(clean.length?'?models='+clean.join(','):''));};
 const selected=ids.map(id=>headphones.find(h=>h.slug===id)!);
 const rows:[string,(h:Headphone)=>string][]=[['Design',h=>h.design],['Fit',h=>h.form],['Connection',h=>h.connection],['ANC',h=>ancLabel(h.anc)],...Object.entries(specLabels).map(([key,label])=>[label,(h:Headphone)=>h.specs[key]||(key==='battery'&&!h.wireless?'Not applicable — passive wired':'Not verified')] as [string,(h:Headphone)=>string]),['Use cases (editorial)',h=>h.uses.join(', ')],['Source reviewed',h=>h.checkedAt]];
 const visibleRows=rows.filter(([,fn])=>!different||selected.length<2||new Set(selected.map(fn)).size>1);
 async function copy(){try{await navigator.clipboard.writeText(window.location.href);setMessage('Comparison link copied.');}catch{setMessage('Copy the comparison URL from your address bar.');}}
 return <><div className="compare-pickers">{Array.from({length:4},(_,i)=><label key={i}>Headphone {i+1}<select aria-label={`Headphone ${i+1}`} value={ids[i]||''} onChange={e=>change(i,e.target.value)}><option value="">{ids[i]?'Remove model':'Select a model'}</option>{[...headphones].sort((a,b)=>(a.brand+a.model).localeCompare(b.brand+b.model)).map(h=><option value={h.slug} key={h.slug} disabled={ids.includes(h.slug)&&ids[i]!==h.slug}>{h.brand} {h.model}</option>)}</select></label>)}</div><div className="compare-controls"><label><input type="checkbox" checked={different} disabled={selected.length<2} onChange={e=>setDifferent(e.target.checked)}/>Show differences only</label><button onClick={copy} disabled={!ids.length}>Copy comparison link</button><button disabled={!ids.length} onClick={()=>{setIds([]);setDifferent(false);setMessage('');window.history.replaceState(null,'','/compare/');}}>Clear selection</button><span role="status" className="copy-status">{message}</span></div>{selected.length?<><p className="small">{selected.length} of 4 models selected. {selected.length<2?'Choose another model to compare.':'Scroll the table horizontally on smaller screens.'}</p><div className="table-wrap" role="region" aria-label="Headphone comparison table" tabIndex={0}><table><caption className="small">Manufacturer specifications; missing values are not inferred.</caption><thead><tr><th scope="col">Specification</th>{selected.map(h=><th scope="col" key={h.slug}><ProductImage h={h}/><Link href={'/headphones/'+h.slug+'/'}>{h.brand}<br/>{h.model}</Link></th>)}</tr></thead><tbody>{visibleRows.map(([label,fn])=><tr key={label}><th scope="row">{label}</th>{selected.map(h=><td key={h.slug}>{fn(h)}</td>)}</tr>)}<tr><th scope="row">Verify at source</th>{selected.map(h=><td key={h.slug}><a href={h.sourceUrl} target="_blank" rel="noopener noreferrer">{h.brand} official page ↗</a></td>)}</tr></tbody></table></div></>:<div className="notice"><h2>Start with two models.</h2><p>Choose up to four above, or open Compare from any profile. Your selection is stored in the page URL for bookmarking and sharing.</p><Link href="/headphones/">Explore the catalogue →</Link></div>}</>;
}
