import type { Headphone } from './headphones';
export const useCases = [
 {slug:'studio',name:'Studio',intro:'Choose for the job in front of you: tracking, editing or checking a mix.',criteria:'Prioritise an analogue connection for direct monitoring, a usable cable and an enclosure suited to the room. Closed headphones help contain a cue mix; open models suit quieter editing sessions.',caution:'Studio is not a sound-quality score. These models are grouped by documented professional applications.',picks:['audio-technica-ath-m50x','beyerdynamic-dt-700-pro-x','audio-technica-ath-r50x']},
 {slug:'mixing',name:'Mixing',intro:'Build a shortlist for focused decisions in a quiet workspace.',criteria:'Start with wired reference-oriented models. Compare enclosure, connection, weight and source requirements, then audition with familiar mixes. Manufacturer frequency limits do not prove neutrality.',caution:'We have not measured frequency response or mix translation. Check decisions on another playback system.',picks:['beyerdynamic-dt-900-pro-x','audio-technica-ath-r70xa','akg-k702']},
 {slug:'recording',name:'Recording',intro:'Keep the cue mix in your ears and away from the microphone.',criteria:'Our recording shortlist uses closed, wired models intended for monitoring. Consider seal, replaceable cables and the reach from your interface to the performer.',caution:'Closed-back does not mean silent outside the earcup. Check bleed at the actual recording level.',picks:['beyerdynamic-dt-770-pro-x','audio-technica-ath-m40x','shure-srh440a']},
 {slug:'audiophile',name:'Audiophile',intro:'Compare designs for deliberate listening at home.',criteria:'Choose an enclosure for your room first. Open headphones let sound pass through; closed and in-ear designs depend heavily on seal. Match connectors and amplifier capability before comparing specifications.',caution:'Larger drivers and wider published frequency ranges are not proof of better sound. Personal audition remains valuable.',picks:['sennheiser-hd-600','sennheiser-ie-200','shure-srh1540']},
 {slug:'travel',name:'Travel',intro:'ANC, practical connections and battery claims in one place.',criteria:'This shortlist requires confirmed active noise cancellation and wireless playback. Check whether your journey needs a wired fallback and compare battery figures only when listening modes match.',caution:'ANC effectiveness and comfort are not independently measured here. Manufacturer battery conditions differ.',picks:['sony-wh-1000xm6','bose-quietcomfort-ultra-headphones-2nd-gen','sennheiser-accentum-plus-wireless']},
 {slug:'commuting',name:'Commuting',intro:'Narrow the options for everyday journeys and changing surroundings.',criteria:'Confirmed ANC and wireless connectivity are the entry criteria. Look for a fit you can use comfortably and controls you can operate without taking out your phone.',caution:'Stay aware of traffic and announcements. Ambient modes are not a guarantee of situational awareness.',picks:['sony-wh-ch720n','sennheiser-accentum-wireless','sony-wh-1000xm5']},
 {slug:'gaming',name:'Gaming',intro:'Start with the connection and microphone your setup actually supports.',criteria:'These are manufacturer-designated gaming headsets with documented microphones. Check your exact console or PC connection; wireless support may need a dongle or adapter.',caution:'We have not measured positional accuracy, microphone clarity or end-to-end latency. Bluetooth support alone does not establish console compatibility.',picks:['beyerdynamic-mmx-300-pro','beyerdynamic-mmx-330-pro','beyerdynamic-mmx-150-wireless']},
 {slug:'calls',name:'Calls',intro:'Compare headsets and wireless headphones with documented voice support.',criteria:'Decide whether you need a boom microphone or the convenience of a built-in microphone. Confirm your meeting app, operating system and connection mode before buying.',caution:'A microphone specification is not a call-quality test. Wired audio modes may not carry the built-in microphone signal.',picks:['beyerdynamic-mmx-300-pro','audio-technica-ath-m50xbt2','sony-wh-1000xm6']},
 {slug:'wireless',name:'Wireless',intro:'Compare Bluetooth features without confusing codecs with sound quality.',criteria:'Check shared codec support between headphones and source. Review playback conditions alongside battery claims. USB charging does not automatically mean USB audio.',caution:'A supported codec is not guaranteed to be active on every device. Real battery life varies with settings, volume and battery age.',picks:['audio-technica-ath-m20xbt','sennheiser-accentum-plus-wireless','sony-wh-1000xm6']},
];
export const categories = [...useCases.map(({slug,name,intro})=>({slug,name,intro})),
 {slug:'open-back',name:'Open-back',intro:'Open enclosures for quieter listening spaces.'},
 {slug:'closed-back',name:'Closed-back',intro:'Enclosed designs for monitoring and everyday listening.'},
 {slug:'in-ear',name:'In-ear',intro:'Compact earphones where tip fit is part of the sound.'},
 {slug:'wired',name:'Wired',intro:'Passive analogue headphones and headsets without a playback battery.'}];
export function inCategory(h: Headphone, slug: string) {return slug === 'wired' ? !h.wireless : slug === 'in-ear' ? h.form === slug : ['open-back','closed-back'].includes(slug) ? h.design === slug : h.uses.includes(slug);}
